package org.example.nuiifo0d.utils;

public class ReasonPhrases {
    public static final String ACCEPTED = "ACCEPTED";
    public static final String BAD_GATEWAY = "BAD_GATEWAY";
    public static final String BAD_REQUEST = "BAD_REQUEST";
    public static final String CONFLICT = "CONFLICT";
    public static final String CONTINUE = "CONTINUE";
    public static final String CREATED = "CREATED";
    public static final String EXPECTATION_FAILED = "EXPECTATION_FAILED";
    public static final String FAILED_DEPENDENCY = "FAILED_DEPENDENCY";
    public static final String FORBIDDEN = "FORBIDDEN";
    public static final String GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT";
    public static final String GONE = "GONE";
    public static final String HTTP_VERSION_NOT_SUPPORTED = "HTTP_VERSION_NOT_SUPPORTED";
    public static final String IM_A_TEAPOT = "IM_A_TEAPOT";
    public static final String INSUFFICIENT_SPACE_ON_RESOURCE = "INSUFFICIENT_SPACE_ON_RESOURCE";
    public static final String INSUFFICIENT_STORAGE = "INSUFFICIENT_STORAGE";
    public static final String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    public static final String LENGTH_REQUIRED = "LENGTH_REQUIRED";
    public static final String LOCKED = "LOCKED";
    public static final String METHOD_FAILURE = "METHOD_FAILURE";
    public static final String METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED";
    public static final String MOVED_PERMANENTLY = "MOVED_PERMANENTLY";
    public static final String MOVED_TEMPORARILY = "MOVED_TEMPORARILY";
    public static final String MULTI_STATUS = "MULTI_STATUS";
    public static final String MULTIPLE_CHOICES = "MULTIPLE_CHOICES";
    public static final String NETWORK_AUTHENTICATION_REQUIRED = "NETWORK_AUTHENTICATION_REQUIRED";
    public static final String NO_CONTENT = "NO_CONTENT";
    public static final String NON_AUTHORITATIVE_INFORMATION = "NON_AUTHORITATIVE_INFORMATION";
    public static final String NOT_ACCEPTABLE = "NOT_ACCEPTABLE";
    public static final String NOT_FOUND = "NOT_FOUND";
    public static final String NOT_IMPLEMENTED = "NOT_IMPLEMENTED";
    public static final String NOT_MODIFIED = "NOT_MODIFIED";
    public static final String OK = "OK";
    public static final String PARTIAL_CONTENT = "PARTIAL_CONTENT";
    public static final String PAYMENT_REQUIRED = "PAYMENT_REQUIRED";
    public static final String PERMANENT_REDIRECT = "PERMANENT_REDIRECT";
    public static final String PRECONDITION_FAILED = "PRECONDITION_FAILED";
    public static final String PRECONDITION_REQUIRED = "PRECONDITION_REQUIRED";
    public static final String PROCESSING = "PROCESSING";
    public static final String PROXY_AUTHENTICATION_REQUIRED = "PROXY_AUTHENTICATION_REQUIRED";
    public static final String REQUEST_HEADER_FIELDS_TOO_LARGE = "REQUEST_HEADER_FIELDS_TOO_LARGE";
    public static final String REQUEST_TIMEOUT = "REQUEST_TIMEOUT";
    public static final String REQUEST_TOO_LONG = "REQUEST_TOO_LONG";
    public static final String REQUEST_URI_TOO_LONG = "REQUEST_URI_TOO_LONG";
    public static final String REQUESTED_RANGE_NOT_SATISFIABLE = "REQUESTED_RANGE_NOT_SATISFIABLE";
    public static final String RESET_CONTENT = "RESET_CONTENT";
    public static final String SEE_OTHER = "SEE_OTHER";
    public static final String SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE";
    public static final String SWITCHING_PROTOCOLS = "SWITCHING_PROTOCOLS";
    public static final String TEMPORARY_REDIRECT = "TEMPORARY_REDIRECT";
    public static final String TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
    public static final String UNAUTHORIZED = "UNAUTHORIZED";
    public static final String UNAVAILABLE_FOR_LEGAL_REASONS = "UNAVAILABLE_FOR_LEGAL_REASONS";
    public static final String UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY";
    public static final String UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE";
    public static final String USE_PROXY = "USE_PROXY";
    public static final String MISDIRECTED_REQUEST = "MISDIRECTED_REQUEST";

}

